#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pgritsen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/10 09:43:40 by pgritsen          #+#    #+#              #
#    Updated: 2017/08/10 09:43:41 by pgritsen         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

APP_NAME = ft_cat

all:$(APP_NAME)

$(APP_NAME):
	@gcc -Wextra -Wall -Werror node.c -o $(APP_NAME)
clean:
	@rm $(APP_NAME)
fclean:clean
	@rm -f $(APP_NAME)