#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pgritsen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/13 10:45:57 by pgritsen          #+#    #+#              #
#    Updated: 2017/08/13 10:45:58 by pgritsen         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = bsq

SRC = input.c node.c output.c utils_llist.c

$(NAME):all

all:
	@gcc -Wextra -Wall -Werror $(SRC) -o $(NAME)

fclean:
	@rm -f $(NAME)
