#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pgritsen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/12 18:43:24 by pgritsen          #+#    #+#              #
#    Updated: 2017/08/12 18:43:26 by pgritsen         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

NAME = eval_expr

SRC =	atoi.c		\
		calculate.c	\
		dntt.c		\
		helpers.c	\
		node.c		\
		output.c	\
		stack.c		\

$(NAME):all

all:
	@gcc -Wextra -Wall -Werror $(SRC) -o $(NAME)

clean:
	@rm -f "FUCK YOU! WITH YOUR FUCKING CLEAN!!!"

.PHONY:fclean

fclean:
	@rm -f $(NAME)
