#******************************************************************************#
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pgritsen <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/08/10 09:08:59 by pgritsen          #+#    #+#              #
#    Updated: 2017/08/10 09:09:00 by pgritsen         ###   ########.fr        #
#                                                                              #
#******************************************************************************#

APP_NAME = ft_display_file

all:$(APP_NAME)

$(APP_NAME):
	@gcc -Wextra -Wall -Werror node.c -o $(APP_NAME)

.PHONY:clean

clean:
	@rm $(APP_NAME)
fclean:
	@rm -f $(APP_NAME)